### ISSUE TITLE
How to access different comparison modes?

### ISSUE THREAD

**Issue by chinchang** [koola/pixel-diff#1]
@koola 
The readme says:
>There are three types of image comparisons:Pixel-by-pixel, Perceptual, and Context.

How can I set the mode of comparison in `pixel-diff` library?

**Comment by koola** [comment]
Hi @chinchang,

Pixel-by-pixel is the default comparison, Perceptual can override default with `options.perceptual: true` in options config.

All options are documented [here](https://github.com/koola/pixel-diff/blob/master/docs/index.md)
